spring:
  application:
    name: turbine-server
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    enable: false
turbine:
  instanceUrlSuffix: :8080/hystrix.stream
  clusterNameExpression: new String("default")
  aggregator:
    clusterConfig: default
InstanceDiscovery:
  impl: com.contaazul.turbine.KubernetesInstanceDiscovery.class



